#!/bin/sh
echo "Making Tachyon $1"
mkdir -p releases/$1
mkdir releases/$1/package
cp tachyon.js releases/$1/tachyon.js

# minify
echo "Making tachyon-min.js with uglifyjs"
touch tachyon-min.js
uglifyjs tachyon.js > tachyon-min.js
cp tachyon-min.js releases/$1/tachyon-min.js
mv tachyon-min.js releases/$1/package/tachyon-min.js

# make package
echo "Making package"
cp tachyon.js releases/$1/package/tachyon.js
cp package.json.template package.json
sed -i "s/SEDME/$1/g" package.json
mv package.json releases/$1/package/package.json

cp LICENSE releases/$1/LICENSE
cp LICENSE releases/$1/package/LICENSE

echo "Tarballing"
cd releases
tar czf $1/tachyon-$1.tar.gz $1/*

echo "Complete! $1"